import Vue from 'vue';

Vue.component( 'f7-modal', require( './modal.vue' ) );
Vue.component( 'f7-content-block', require( './content-block.vue' ) );
Vue.component( 'f7-views', require( './views.vue' ) );
Vue.component( 'f7-view', require( './view.vue' ) );
Vue.component( 'f7-pages', require( './pages.vue' ) );
Vue.component( 'f7-page', require( './page.vue' ) );
Vue.component( 'f7-page-content', require( './page-content.vue' ) );
Vue.component( 'f7-navbar', require( './navbar.vue' ) );
Vue.component( 'f7-toolbar', require( './toolbar.vue' ) );
Vue.component( 'f7-toolbar-item', require( './toolbar-item.vue' ) );
Vue.component( 'f7-tabbar', require( './tabbar.vue' ) );
Vue.component( 'f7-tabbar-item', require( './tabbar-item.vue' ) );
Vue.component( 'f7-tabbar-label', require( './tabbar-label.vue' ) );
Vue.component( 'f7-badge', require( './badge.vue' ) );
Vue.component( 'f7-icon', require( './icon.vue' ) );
Vue.component( 'f7-searchbar', require( './searchbar.vue' ) );
Vue.component( 'f7-side', require( './side.vue' ) );
Vue.component( 'f7-row', require( './row.vue' ) );
Vue.component( 'f7-col', require( './col.vue' ) );
Vue.component( 'f7-popup', require( './popup.vue' ) );
